In [1]:
import numpy as np
from numpy import array
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

import math

from keras.callbacks import EarlyStopping
from keras.models import Sequential

from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import SimpleRNN
from keras.layers import Dropout
from sklearn.model_selection import train_test_split

import tensorflow.keras.backend as K

In [2]:
dataset = pd.read_csv("Datasets1/combined_report_Kocani.csv")

In [4]:
dataset = dataset.drop(columns = ["ozone", "precipAccumulation", "precipIntensity", "precipProbability", "pressure", "visibility", "PM10", "NO2", "O3", "PM25", "SO2", "AQI"])

In [5]:
target = dataset["CO"]

In [6]:
target

0       1.0300
1       1.3600
2       1.1500
3       1.0300
4       0.8500
         ...  
7767    1.2412
7768    1.0092
7769    1.1716
7770    1.5892
7771    1.0440
Name: CO, Length: 7772, dtype: float64

In [7]:
features = dataset.drop(columns = ["CO"])

In [8]:
features

apparentTemperature  cloudCover  dewPoint  humidity  \
0                   10.55        1.00      4.50      0.56   
1                    3.99        1.00      4.50      0.72   
2                   12.55        0.38      5.91      0.74   
3                   16.55        0.38      7.30      0.55   
4                   27.83        0.38      7.30      0.41   
...                   ...         ...       ...       ...   
7767                25.35        0.04     23.39      0.92   
7768                24.46        0.03     22.93      0.94   
7769                23.89        0.04     22.65      0.95   
7770                31.17        0.06     26.79      0.84   
7771                29.84        0.07     26.13      0.86   

                     icon precipType        summary  temperature        time  \
0             clear-night       snow          Clear        17.39  1420135200   
1             clear-night       snow          Clear        11.76  1420167600   
2     partly-cloudy-night       snow  Partly Cloudy        12.55  1420178400   
3       partly-cloudy-day       snow  Partly Cloudy        20.99  1420189200   
4       partly-cloudy-day       snow  Partly Cloudy        27.83  1420200000   
...                   ...        ...            ...          ...         ...   
7767          clear-night       snow          Clear        25.35  1546117200   
7768          clear-night       snow          Clear        24.46  1546120800   
7769          clear-night       snow          Clear        23.89  1546124400   
7770          clear-night       snow          Clear        31.17  1546128000   
7771          clear-night       snow          Clear        29.84  1546131600   

      uvIndex  windBearing  windGust  windSpeed  
0         0.0          0.0      3.19       4.48  
1         0.0         20.0      3.19       4.48  
2         0.0         45.0      3.19       2.24  
3         1.0        213.0      3.19       3.19  
4         1.0        235.0      3.19       2.24  
...       ...          ...       ...        ...  
7767      0.0        350.0      3.88       2.76  
7768      0.0        350.0      3.61       2.60  
7769      0.0        350.0      3.76       2.68  
7770      0.0         24.0      3.77       2.37  
7771      0.0         20.0      3.46       2.30  

[7772 rows x 13 columns]

In [27]:
model0 = Sequential()
model0.add(SimpleRNN(units=50, activation='relu', input_shape=(2200, 10)))
model0.add(Dense(1))
model0.compile(optimizer='adam', loss='mse')
print(model0.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 50)                3050      
                                                                 
 dense_1 (Dense)             (None, 1)                 51        
                                                                 
Total params: 3,101
Trainable params: 3,101
Non-trainable params: 0
_________________________________________________________________
None


In [10]:
dataset_bez_stringovi = dataset.drop(columns = ["icon", "precipType", "summary"])

In [11]:
dataset_bez_stringovi

apparentTemperature  cloudCover  dewPoint  humidity  temperature  \
0                   10.55        1.00      4.50      0.56        17.39   
1                    3.99        1.00      4.50      0.72        11.76   
2                   12.55        0.38      5.91      0.74        12.55   
3                   16.55        0.38      7.30      0.55        20.99   
4                   27.83        0.38      7.30      0.41        27.83   
...                   ...         ...       ...       ...          ...   
7767                25.35        0.04     23.39      0.92        25.35   
7768                24.46        0.03     22.93      0.94        24.46   
7769                23.89        0.04     22.65      0.95        23.89   
7770                31.17        0.06     26.79      0.84        31.17   
7771                29.84        0.07     26.13      0.86        29.84   

            time  uvIndex  windBearing  windGust  windSpeed      CO  
0     1420135200      0.0          0.0      3.19       4.48  1.0300  
1     1420167600      0.0         20.0      3.19       4.48  1.3600  
2     1420178400      0.0         45.0      3.19       2.24  1.1500  
3     1420189200      1.0        213.0      3.19       3.19  1.0300  
4     1420200000      1.0        235.0      3.19       2.24  0.8500  
...          ...      ...          ...       ...        ...     ...  
7767  1546117200      0.0        350.0      3.88       2.76  1.2412  
7768  1546120800      0.0        350.0      3.61       2.60  1.0092  
7769  1546124400      0.0        350.0      3.76       2.68  1.1716  
7770  1546128000      0.0         24.0      3.77       2.37  1.5892  
7771  1546131600      0.0         20.0      3.46       2.30  1.0440  

[7772 rows x 11 columns]

In [12]:
features_bez_stringovi = dataset_bez_stringovi.drop(columns = ["CO"])

In [13]:
features_bez_stringovi

apparentTemperature  cloudCover  dewPoint  humidity  temperature  \
0                   10.55        1.00      4.50      0.56        17.39   
1                    3.99        1.00      4.50      0.72        11.76   
2                   12.55        0.38      5.91      0.74        12.55   
3                   16.55        0.38      7.30      0.55        20.99   
4                   27.83        0.38      7.30      0.41        27.83   
...                   ...         ...       ...       ...          ...   
7767                25.35        0.04     23.39      0.92        25.35   
7768                24.46        0.03     22.93      0.94        24.46   
7769                23.89        0.04     22.65      0.95        23.89   
7770                31.17        0.06     26.79      0.84        31.17   
7771                29.84        0.07     26.13      0.86        29.84   

            time  uvIndex  windBearing  windGust  windSpeed  
0     1420135200      0.0          0.0      3.19       4.48  
1     1420167600      0.0         20.0      3.19       4.48  
2     1420178400      0.0         45.0      3.19       2.24  
3     1420189200      1.0        213.0      3.19       3.19  
4     1420200000      1.0        235.0      3.19       2.24  
...          ...      ...          ...       ...        ...  
7767  1546117200      0.0        350.0      3.88       2.76  
7768  1546120800      0.0        350.0      3.61       2.60  
7769  1546124400      0.0        350.0      3.76       2.68  
7770  1546128000      0.0         24.0      3.77       2.37  
7771  1546131600      0.0         20.0      3.46       2.30  

[7772 rows x 10 columns]

In [14]:
dataset_train = dataset_bez_stringovi[:-2000]

In [15]:
dataset_train

apparentTemperature  cloudCover  dewPoint  humidity  temperature  \
0                   10.55        1.00      4.50      0.56        17.39   
1                    3.99        1.00      4.50      0.72        11.76   
2                   12.55        0.38      5.91      0.74        12.55   
3                   16.55        0.38      7.30      0.55        20.99   
4                   27.83        0.38      7.30      0.41        27.83   
...                   ...         ...       ...       ...          ...   
5767                38.77        0.50     30.32      0.61        42.71   
5768                35.38        0.50     30.22      0.67        40.34   
5769                37.40        0.80     32.21      0.69        41.57   
5770                45.57        0.88     33.63      0.59        47.45   
5771                55.16        0.88     36.04      0.48        55.16   

            time  uvIndex  windBearing  windGust  windSpeed    CO  
0     1420135200      0.0          0.0      3.19       4.48  1.03  
1     1420167600      0.0         20.0      3.19       4.48  1.36  
2     1420178400      0.0         45.0      3.19       2.24  1.15  
3     1420189200      1.0        213.0      3.19       3.19  1.03  
4     1420200000      1.0        235.0      3.19       2.24  0.85  
...          ...      ...          ...       ...        ...   ...  
5767  1513296000      0.0         64.0      3.19       6.37  0.61  
5768  1513306800      0.0         89.0      3.19       7.30  0.65  
5769  1513317600      0.0         83.0      3.19       6.37  0.53  
5770  1513328400      1.0        112.0      3.19       4.48  2.29  
5771  1513339200      1.0        211.0      3.19      10.06  2.31  

[5772 rows x 11 columns]

In [16]:
dataset_test = dataset_bez_stringovi[-2000:]

In [17]:
dataset_test

apparentTemperature  cloudCover  dewPoint  humidity  temperature  \
5772                54.63        0.88     34.56      0.47        54.63   
5773                56.78        1.00     40.42      0.54        56.78   
5774                52.00        1.00     44.85      0.77        52.00   
5775                46.24        1.00     43.34      0.82        48.53   
5776                43.12        1.00     42.24      0.89        45.35   
...                   ...         ...       ...       ...          ...   
7767                25.35        0.04     23.39      0.92        25.35   
7768                24.46        0.03     22.93      0.94        24.46   
7769                23.89        0.04     22.65      0.95        23.89   
7770                31.17        0.06     26.79      0.84        31.17   
7771                29.84        0.07     26.13      0.86        29.84   

            time  uvIndex  windBearing  windGust  windSpeed      CO  
5772  1513350000      0.0        161.0      3.19      10.62  3.1800  
5773  1513436400      0.0        164.0      3.19      11.18  0.9400  
5774  1513447200      0.0        108.0      3.19       6.13  1.1000  
5775  1513458000      0.0          0.0      3.19       5.42  1.4500  
5776  1513468800      0.0        339.0      3.19       4.48  0.4500  
...          ...      ...          ...       ...        ...     ...  
7767  1546117200      0.0        350.0      3.88       2.76  1.2412  
7768  1546120800      0.0        350.0      3.61       2.60  1.0092  
7769  1546124400      0.0        350.0      3.76       2.68  1.1716  
7770  1546128000      0.0         24.0      3.77       2.37  1.5892  
7771  1546131600      0.0         20.0      3.46       2.30  1.0440  

[2000 rows x 11 columns]

In [18]:
scaler = MinMaxScaler() #default od 0 do 1
dataset_train = scaler.fit_transform(dataset_train)
dataset_test = scaler.fit_transform(dataset_test)

In [21]:
dataset_train.shape

(5772, 11)

In [22]:
dataset_train = np.reshape(dataset_train, (5772,11))
dataset_test = np.reshape(dataset_test, (2000,11))

In [23]:
# split a multivariate sequence into samples
def split_sequences(sequences, n_steps):
	X, y = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [24]:
# choose a number of time steps
n_steps = 2200
# convert into input/output
X, y = split_sequences(dataset_train, n_steps)
print(X.shape, y.shape)
# the dataset knows the number of features, e.g. 2
n_features = X.shape[2]
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

(3573, 2200, 10) (3573,)
[[0.1214926  1.         0.02197273 ... 0.         0.         0.19840567]
 [0.05757989 1.         0.02197273 ... 0.05571031 0.         0.19840567]
 [0.14097818 0.28735632 0.04458701 ... 0.12534819 0.         0.        ]
 ...
 [0.73889322 0.42528736 0.94819567 ... 0.25626741 0.         0.19840567]
 [0.69232268 0.71264368 0.89382518 ... 0.30640669 0.         0.19840567]
 [0.65237724 1.         0.90264635 ... 0.30640669 0.         0.19840567]] 0.03015075376884422
[[0.05757989 1.         0.02197273 ... 0.05571031 0.         0.19840567]
 [0.14097818 0.28735632 0.04458701 ... 0.12534819 0.         0.        ]
 [0.17994934 0.28735632 0.06688051 ... 0.59331476 0.         0.08414526]
 ...
 [0.69232268 0.71264368 0.89382518 ... 0.30640669 0.         0.19840567]
 [0.65237724 1.         0.90264635 ... 0.30640669 0.         0.19840567]
 [0.74395947 1.         0.91964715 ... 0.23398329 0.         0.        ]] 0.030778894472361807
[[0.14097818 0.28735632 0.04458701 ... 0.12534

 [0.83437256 0.65517241 0.76182839 ... 0.62674095 0.         0.55535872]] 0.06155778894472361
[[0.39760327 1.         0.4574178  ... 0.93036212 0.         0.16740478]
 [0.42653936 1.         0.4659182  ... 0.61559889 0.         0.        ]
 [0.36866719 1.         0.48019246 ... 0.8913649  0.         0.19840567]
 ...
 [0.78020265 0.24137931 0.78893344 ... 0.59052925 0.         0.29583702]
 [0.83437256 0.65517241 0.76182839 ... 0.62674095 0.         0.55535872]
 [0.84197194 0.86206897 0.74707298 ... 0.62674095 0.         0.24889283]] 0.034547738693467334
[[0.42653936 1.         0.4659182  ... 0.61559889 0.         0.        ]
 [0.36866719 1.         0.48019246 ... 0.8913649  0.         0.19840567]
 [0.38805534 1.         0.48019246 ... 0.8913649  0.         0.        ]
 ...
 [0.83437256 0.65517241 0.76182839 ... 0.62674095 0.         0.55535872]
 [0.84197194 0.86206897 0.74707298 ... 0.62674095 0.         0.24889283]
 [0.7566251  1.         0.80481155 ... 0.42061281 0.         0.37998229

 [0.52279813 0.66666667 0.44186047 ... 0.08077994 0.         0.43932684]] 0.0621859296482412
[[0.58602884 1.         0.78364074 ... 0.94986072 0.         0.19840567]
 [0.56780982 0.75862069 0.80272654 ... 0.96657382 0.         0.16740478]
 [0.53858145 0.86206897 0.71114675 ... 0.90529248 0.         0.16740478]
 ...
 [0.56342557 0.82758621 0.47810746 ... 0.02785515 0.         0.62533215]
 [0.52279813 0.66666667 0.44186047 ... 0.08077994 0.         0.43932684]
 [0.45060405 0.42528736 0.44314354 ... 0.04735376 0.         0.44464128]] 0.07600502512562814
[[0.56780982 0.75862069 0.80272654 ... 0.96657382 0.         0.16740478]
 [0.53858145 0.86206897 0.71114675 ... 0.90529248 0.         0.16740478]
 [0.58076773 0.86206897 0.76022454 ... 0.94986072 0.         0.16740478]
 ...
 [0.52279813 0.66666667 0.44186047 ... 0.08077994 0.         0.43932684]
 [0.45060405 0.42528736 0.44314354 ... 0.04735376 0.         0.44464128]
 [0.416212   0.68965517 0.44282277 ... 0.10306407 0.         0.29406554]]

 [0.23168355 0.7816092  0.24795509 ... 0.01949861 0.         0.19840567]] 0.0772613065326633
[[0.63172253 0.86206897 0.87008821 ... 0.79665738 0.         0.19840567]
 [0.62519486 0.91954023 0.90729751 ... 0.94986072 0.         0.16740478]
 [0.59957132 0.91954023 0.8734563  ... 0.90250696 0.         0.2506643 ]
 ...
 [0.20099376 0.13793103 0.12381716 ... 0.32869081 0.         0.02302923]
 [0.23168355 0.7816092  0.24795509 ... 0.01949861 0.         0.19840567]
 [0.31566641 0.3908046  0.29286287 ... 0.70194986 0.         0.36846767]] 0.05464824120603014
[[0.62519486 0.91954023 0.90729751 ... 0.94986072 0.         0.16740478]
 [0.59957132 0.91954023 0.8734563  ... 0.90250696 0.         0.2506643 ]
 [0.64370616 0.86206897 0.85838011 ... 0.94986072 0.         0.16740478]
 ...
 [0.23168355 0.7816092  0.24795509 ... 0.01949861 0.         0.19840567]
 [0.31566641 0.3908046  0.29286287 ... 0.70194986 0.         0.36846767]
 [0.30300078 0.83908046 0.21074579 ... 0.61002786 0.         0.23649247]]

 [0.43949727 0.87356322 0.52093023 ... 0.25069638 0.         0.19840567]] 0.11746231155778894
[[0.90578722 0.06896552 0.75396953 ... 0.78830084 0.         0.39681134]
 [0.91319174 0.13793103 0.77257418 ... 0.50139276 0.         0.19840567]
 [0.82521434 0.28735632 0.82485966 ... 0.33426184 0.         0.16474756]
 ...
 [0.42692907 1.         0.48821171 ... 0.22841226 0.         0.36581045]
 [0.43949727 0.87356322 0.52093023 ... 0.25069638 0.         0.19840567]
 [0.46219797 1.         0.5446672  ... 0.28133705 0.         0.56333038]] 0.12562814070351758
[[0.91319174 0.13793103 0.77257418 ... 0.50139276 0.         0.19840567]
 [0.82521434 0.28735632 0.82485966 ... 0.33426184 0.         0.16474756]
 [0.76724474 0.24137931 0.81122694 ... 0.3091922  0.         0.31355182]
 ...
 [0.43949727 0.87356322 0.52093023 ... 0.25069638 0.         0.19840567]
 [0.46219797 1.         0.5446672  ... 0.28133705 0.         0.56333038]
 [0.55475448 0.75862069 0.57722534 ... 0.38997214 0.         0.37909655]

 [0.34713562 0.42528736 0.40769848 ... 0.1810585  0.         0.21612046]] 0.04020100502512562
[[0.40208496 1.         0.62117081 ... 0.         0.         0.59521701]
 [0.41299688 1.         0.63416199 ... 0.0362117  0.         0.71656333]
 [0.44086126 1.         0.65164395 ... 0.01671309 0.         0.43489814]
 ...
 [0.32862432 0.86206897 0.36840417 ... 0.23119777 0.         0.36581045]
 [0.34713562 0.42528736 0.40769848 ... 0.1810585  0.         0.21612046]
 [0.52796181 0.37931034 0.46816359 ... 0.57938719 0.         0.33746678]] 0.03580402010050251
[[0.41299688 1.         0.63416199 ... 0.0362117  0.         0.71656333]
 [0.44086126 1.         0.65164395 ... 0.01671309 0.         0.43489814]
 [0.44397896 1.         0.65629511 ... 0.12256267 0.         0.53941541]
 ...
 [0.34713562 0.42528736 0.40769848 ... 0.1810585  0.         0.21612046]
 [0.52796181 0.37931034 0.46816359 ... 0.57938719 0.         0.33746678]
 [0.61886204 0.67816092 0.44538893 ... 0.66852368 0.         0.41629761]

 [0.60911925 1.         0.68019246 ... 0.23955432 0.         0.16740478]] 0.034547738693467334
[[0.40481294 1.         0.49238172 ... 0.80779944 0.         0.        ]
 [0.44115355 0.72413793 0.54081796 ... 0.59888579 0.         0.        ]
 [0.4102689  1.         0.53231756 ... 0.02506964 0.         0.        ]
 ...
 [0.61740062 0.88505747 0.6542101  ... 0.33426184 0.         0.79273694]
 [0.60911925 1.         0.68019246 ... 0.23955432 0.         0.16740478]
 [0.68998441 1.         0.70168404 ... 0.30362117 0.         0.19840567]] 0.034547738693467334
[[0.44115355 0.72413793 0.54081796 ... 0.59888579 0.         0.        ]
 [0.4102689  1.         0.53231756 ... 0.02506964 0.         0.        ]
 [0.39078332 1.         0.51371291 ... 0.90529248 0.         0.        ]
 ...
 [0.60911925 1.         0.68019246 ... 0.23955432 0.         0.16740478]
 [0.68998441 1.         0.70168404 ... 0.30362117 0.         0.19840567]
 [0.72895557 1.         0.7010425  ... 0.63509749 0.         0.1984056

 [0.75467654 0.63218391 0.87730553 ... 0.64066852 0.         0.06997343]] 0.031407035175879394
[[0.6962198  0.13793103 0.96535686 ... 0.89693593 0.         0.19840567]
 [0.83369057 0.77011494 0.92878909 ... 0.39554318 0.         0.36581045]
 [0.79393998 0.8045977  0.89558941 ... 0.07520891 0.         0.41718335]
 ...
 [0.67916991 0.32183908 0.8755413  ... 0.1281337  0.         0.39681134]
 [0.75467654 0.63218391 0.87730553 ... 0.64066852 0.         0.06997343]
 [0.78293063 0.74712644 0.92285485 ... 0.92479109 0.         0.23649247]] 0.0207286432160804
[[0.83369057 0.77011494 0.92878909 ... 0.39554318 0.         0.36581045]
 [0.79393998 0.8045977  0.89558941 ... 0.07520891 0.         0.41718335]
 [0.73070928 0.45977011 0.94129912 ... 0.6545961  0.         0.28166519]
 ...
 [0.75467654 0.63218391 0.87730553 ... 0.64066852 0.         0.06997343]
 [0.78293063 0.74712644 0.92285485 ... 0.92479109 0.         0.23649247]
 [0.72038192 0.86206897 0.93456295 ... 0.1643454  0.         0.39681134]

 [0.75311769 1.         0.86463512 ... 0.12534819 0.         0.06997343]] 0.03391959798994974
[[0.67839049 0.13793103 0.85100241 ... 0.13091922 0.         0.        ]
 [0.79637568 0.20689655 0.91563753 ... 0.68802228 0.         0.19840567]
 [0.85337101 0.49425287 0.83111468 ... 0.08077994 0.         0.36846767]
 ...
 [0.69076383 1.         0.81138733 ... 0.15041783 0.         0.19840567]
 [0.75311769 1.         0.86463512 ... 0.12534819 0.         0.06997343]
 [0.96034684 0.12643678 0.75621492 ... 0.05292479 0.         0.39681134]] 0.03957286432160803
[[0.79637568 0.20689655 0.91563753 ... 0.68802228 0.         0.19840567]
 [0.85337101 0.49425287 0.83111468 ... 0.08077994 0.         0.36846767]
 [0.66923227 1.         0.89382518 ... 0.1810585  0.         0.29583702]
 ...
 [0.75311769 1.         0.86463512 ... 0.12534819 0.         0.06997343]
 [0.96034684 0.12643678 0.75621492 ... 0.05292479 0.         0.39681134]
 [0.88308652 0.08045977 0.76936648 ... 0.26183844 0.         0.26040744]

 [0.69699922 0.75862069 0.84939856 ... 0.57660167 0.         0.59521701]] 0.04459798994974874
[[0.55222136 0.57471264 0.78059342 ... 0.32590529 0.         0.39681134]
 [0.55144193 0.86206897 0.74161989 ... 0.3091922  0.         0.39681134]
 [0.55348792 0.71264368 0.76728148 ... 0.09749304 0.         0.19840567]
 ...
 [0.69544037 0.29885057 0.82421812 ... 0.46239554 0.         0.66519043]
 [0.69699922 0.75862069 0.84939856 ... 0.57660167 0.         0.59521701]
 [0.7744544  0.5862069  0.80465116 ... 0.6545961  0.         0.97431355]] 0.04082914572864321
[[0.55144193 0.86206897 0.74161989 ... 0.3091922  0.         0.39681134]
 [0.55348792 0.71264368 0.76728148 ... 0.09749304 0.         0.19840567]
 [0.63990647 0.71264368 0.73680834 ... 0.44846797 0.         0.39681134]
 ...
 [0.69699922 0.75862069 0.84939856 ... 0.57660167 0.         0.59521701]
 [0.7744544  0.5862069  0.80465116 ... 0.6545961  0.         0.97431355]
 [0.81060016 0.83908046 0.80176423 ... 0.6908078  0.         0.52258636]

 [0.52231099 0.         0.57722534 ... 0.80222841 0.         0.39681134]] 0.0829145728643216
[[0.4109509  0.87356322 0.4064154  ... 0.77715877 0.         0.30735164]
 [0.3910756  1.         0.42004812 ... 0.87465181 0.         0.52081488]
 [0.37412315 0.75862069 0.4287089  ... 0.70752089 0.         0.53941541]
 ...
 [0.36048324 1.         0.51403368 ... 0.07520891 0.         0.59521701]
 [0.52231099 0.         0.57722534 ... 0.80222841 0.         0.39681134]
 [0.62714341 0.40229885 0.54707298 ... 0.77994429 0.         0.54650133]] 0.07035175879396983
[[0.3910756  1.         0.42004812 ... 0.87465181 0.         0.52081488]
 [0.37412315 0.75862069 0.4287089  ... 0.70752089 0.         0.53941541]
 [0.3606781  0.77011494 0.43753007 ... 0.8913649  0.         0.56067316]
 ...
 [0.52231099 0.         0.57722534 ... 0.80222841 0.         0.39681134]
 [0.62714341 0.40229885 0.54707298 ... 0.77994429 0.         0.54650133]
 [0.61740062 0.57471264 0.61154771 ... 0.9637883  0.         0.19840567]]

 [0.56995323 0.86206897 0.57497995 ... 0.57660167 0.         0.19840567]] 0.10615577889447235
[[0.41397116 0.72413793 0.47682438 ... 0.05849582 0.         0.61647476]
 [0.36525721 0.93103448 0.44234162 ... 0.07799443 0.         0.62533215]
 [0.35210444 0.93103448 0.4500401  ... 0.08356546 0.         0.49424269]
 ...
 [0.37879969 0.49425287 0.48067362 ... 0.29247911 0.         0.26660762]
 [0.56995323 0.86206897 0.57497995 ... 0.57660167 0.         0.19840567]
 [0.46853079 0.87356322 0.57433841 ... 0.75208914 0.         0.19840567]] 0.1388190954773869
[[0.36525721 0.93103448 0.44234162 ... 0.07799443 0.         0.62533215]
 [0.35210444 0.93103448 0.4500401  ... 0.08356546 0.         0.49424269]
 [0.33330086 0.86206897 0.45838011 ... 0.07520891 0.         0.59521701]
 ...
 [0.56995323 0.86206897 0.57497995 ... 0.57660167 0.         0.19840567]
 [0.46853079 0.87356322 0.57433841 ... 0.75208914 0.         0.19840567]
 [0.47992985 0.26436782 0.57530072 ... 0.29247911 0.         0.03897254]]

In [28]:
# fit model
model0.fit(X, y, epochs=10, verbose=0)

In [29]:
dataset_test.shape

(2000, 11)

In [31]:
dataset_test = np.reshape(dataset_test, (1, n_steps, n_features))
prediction = model0.predict(dataset_test, verbose=0)
print (prediction)

[[0.04929433]]
